### ISSUE TITLE
readme add how to pull

### ISSUE THREAD

**Issue by super-crayfish** [missuo/FreeDuckDuckGo#1]
docker pull ghcr.io/missuo/freeduckduckgo:latest

linux/amd64
$ docker pull ghcr.io/missuo/freeduckduckgo:latest@sha256:20811de44faa09b25a7486e4a8bcf1d0d0ac319285b226629bee46c7cab5d4b3
linux/arm64
$ docker pull ghcr.io/missuo/freeduckduckgo:latest@sha256:4b683f94790d87790e89af29078605dbcfb289bd04604c143e8565d1f78681af
unknown/unknown
$ docker pull ghcr.io/missuo/freeduckduckgo:latest@sha256:8dd7c64441846ff2a9b4c3a648fd293bb29e6cddb41999c5cd5ed0a85b103957

**Comment by missuo** [comment]
You don't need to use this command. You just run this:

```bash
wget -O compose.yaml https://github.com/missuo/FreeDuckDuckGo/raw/main/compose.yaml
docker compose up -d
```
