### ISSUE TITLE
空包

### ISSUE THREAD

**Issue by workmengxue** [missuo/FreeDuckDuckGo#3]
mkdir FreeDuckDuckGo && cd FreeDuckDuckGo
wget -O compose.yaml https://raw.githubusercontent.com/missuo/FreeDuckDuckGo/main/compose/compose.yaml

输出
root@92:~/FreeDuckDuckGo# wget -O compose.yaml https://raw.githubusercontent.com/missuo/FreeDuckDuckGo/main/compose/compose.yaml
--2024-04-26 01:33:34--  https://raw.githubusercontent.com/missuo/FreeDuckDuckGo/main/compose/compose.yaml
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-04-26 01:33:34 ERROR 404: Not Found.

**Comment by missuo** [comment]
try again
